env.SAST_GIT_URL=""
env.BUILD_GIT_URL=""
env.DAST_IP=""
env.Deployment=""
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/FlexibPlus/web_auto.git"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/FlexibPlus/web_auto.git"
env.JMETER_GIT_URL=""
env.EMAIL_ID=""
