env.SAST_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.BUILD_GIT_URL="https://github.com/harishpallapu/SourceCode_SAST.git"
env.TOMCAT_IP="http://43.204.5.162:8084/"
env.FUNCTIONAL_WEB_GIT_URL="https://github.com/harishpallapu/NuReCampus.git -b master"
env.FUNCTIONAL_MOBILE_GIT_URL="https://github.com/harishpallapu/mobiletest.git"
env.JMETER_GIT_URL="https://github.com/harishpallapu/folder.git"
env.NEXUS_IP="flexib08@gmail.com"
